project_id = "trvuidenkjqqlwadlosh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_email = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54327

[functions.extract-pdf-text]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.youtube-extractor]
verify_jwt = false

[functions.extract-word-text]
verify_jwt = false

[functions.openai-room-chat]
verify_jwt = true

[functions.openai-chat-content]
verify_jwt = true

[functions.openai-generate-exam]
verify_jwt = true

[functions.openai-evaluate-exam]
verify_jwt = true

[functions.openai-exam-chat]
verify_jwt = true

[functions.audio-transcription]
verify_jwt = false

[functions.real-time-transcription]
verify_jwt = false