import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.0';
import { fetchWithRetry, logRetryMetrics } from '../_shared/retryUtils.ts';
import { normalizeTranscript } from '../_shared/transcriptNormalization.ts';
import { 
  extractYouTubeTranscript, 
  extractChapterTranscripts as extractChapterTranscriptsFromSegments,
  TranscriptSegment 
} from '../_shared/youtubeTranscript.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface YouTubeExtractorRequest {
  url: string;
  contentId: string;
}

interface YouTubeData {
  title: string;
  description: string;
  duration: number;
  transcript: string;
  transcriptSegments: TranscriptSegment[];
  chapters: Array<{
    title: string;
    startTime: number;
    endTime?: number;
    transcript?: string;
  }>;
  metadata: {
    videoId: string;
    publishedAt: string;
    channelTitle: string;
    viewCount: string;
    thumbnails: any;
    hasRealTranscript: boolean;
    transcriptSource: string;
    transcriptLanguage: string;
    isAutoGenerated: boolean;
  };
}

function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
    /youtube\.com\/v\/([^&\n?#]+)/
  ];
  
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

function parseChaptersFromDescription(description: string): Array<{title: string; startTime: number; endTime?: number}> {
  const chapters = [];
  const lines = description.split('\n');
  
  const timestampPattern = /^(\d{1,2}:)?(\d{1,2}):(\d{2})\s+(.+)/;
  
  for (const line of lines) {
    const match = line.trim().match(timestampPattern);
    if (match) {
      const hours = match[1] ? parseInt(match[1].replace(':', '')) : 0;
      const minutes = parseInt(match[2]);
      const seconds = parseInt(match[3]);
      const title = match[4].trim();
      
      const startTime = hours * 3600 + minutes * 60 + seconds;
      chapters.push({ title, startTime });
    }
  }
  
  for (let i = 0; i < chapters.length - 1; i++) {
    chapters[i].endTime = chapters[i + 1].startTime;
  }
  
  return chapters;
}

function parseDuration(duration: string): number {
  const match = duration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;
  
  const hours = parseInt(match[1]) || 0;
  const minutes = parseInt(match[2]) || 0;
  const seconds = parseInt(match[3]) || 0;
  
  return hours * 3600 + minutes * 60 + seconds;
}

async function getYouTubeData(videoId: string): Promise<YouTubeData> {
  const apiKey = Deno.env.get('YOUTUBE_API_KEY');
  const supadataApiKey = Deno.env.get('SUPADATA_API_KEY');
  
  if (!apiKey) {
    throw new Error('YouTube API key not configured');
  }

  // Fetch video metadata with retry logic
  const startTime = Date.now();
  const videoResponse = await fetchWithRetry(
    `https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=${videoId}&key=${apiKey}`,
    { method: 'GET' },
    {
      maxRetries: 3,
      timeoutMs: 30000,
      onRetry: (attempt, error) => {
        console.log(`YouTube API retry ${attempt}: ${error.message}`);
      }
    }
  );
  
  logRetryMetrics('youtube_api_video', 1, videoResponse.ok, Date.now() - startTime);
  
  if (!videoResponse.ok) {
    throw new Error(`YouTube API error: ${videoResponse.status}`);
  }
  
  const videoData = await videoResponse.json();
  
  if (!videoData.items || videoData.items.length === 0) {
    throw new Error('Video not found or not accessible');
  }
  
  const video = videoData.items[0];
  const duration = parseDuration(video.contentDetails.duration);
  
  // Use the new transcript extraction module with Supadata + fallback
  console.log('Extracting transcript with Supadata + timedtext fallback...');
  const transcriptResult = await extractYouTubeTranscript(videoId, {
    supadataApiKey: supadataApiKey || undefined,
    preferredLang: 'en',
    fallbackDescription: video.snippet.description
  });
  
  console.log(`Transcript extraction: source=${transcriptResult.source}, segments=${transcriptResult.segments.length}, chars=${transcriptResult.metadata.characterCount}`);
  
  // Parse chapters from description
  const rawChapters = parseChaptersFromDescription(video.snippet.description);
  
  // Extract chapter-specific transcripts from timestamped segments
  const chapters = transcriptResult.segments.length > 0
    ? extractChapterTranscriptsFromSegments(transcriptResult.segments, rawChapters)
    : rawChapters.map(ch => ({ ...ch, transcript: '' }));
  
  const hasRealTranscript = transcriptResult.source !== 'description' && 
                            transcriptResult.source !== 'none' &&
                            transcriptResult.transcript.length > 0;
  
  return {
    title: video.snippet.title,
    description: video.snippet.description,
    duration,
    transcript: transcriptResult.transcript,
    transcriptSegments: transcriptResult.segments,
    chapters,
    metadata: {
      videoId,
      publishedAt: video.snippet.publishedAt,
      channelTitle: video.snippet.channelTitle,
      viewCount: video.statistics.viewCount,
      thumbnails: video.snippet.thumbnails,
      hasRealTranscript,
      transcriptSource: transcriptResult.source,
      transcriptLanguage: transcriptResult.language,
      isAutoGenerated: transcriptResult.isAutoGenerated
    }
  };
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // ========== IP-BASED RATE LIMITING ==========
    const clientIP = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 
                     req.headers.get('x-real-ip') || 
                     'unknown';
    
    console.log('YouTube extractor request from IP:', clientIP);

    const { data: rateCheck, error: rateError } = await supabase.rpc('check_ip_rate_limit', {
      p_ip_address: clientIP,
      p_endpoint: 'youtube-extractor',
      p_max_requests: 20,  // 20 requests per hour
      p_window_minutes: 60
    });

    if (rateError) {
      console.error('Rate limit check error:', rateError);
      // Continue anyway - don't block on rate limit errors
    } else if (rateCheck && rateCheck.length > 0 && !rateCheck[0].allowed) {
      console.log('Rate limit exceeded for IP:', clientIP);
      return new Response(
        JSON.stringify({ 
          success: false,
          error: 'Rate limit exceeded. Please try again later.',
          reset_time: rateCheck[0].reset_time
        }),
        { 
          status: 429, 
          headers: { 
            ...corsHeaders, 
            'Content-Type': 'application/json',
            'Retry-After': '3600'
          } 
        }
      );
    }

    const { url, contentId }: YouTubeExtractorRequest = await req.json();
    
    console.log('Extracting YouTube data for:', url);
    
    const videoId = extractVideoId(url);
    if (!videoId) {
      throw new Error('Invalid YouTube URL');
    }

    // Update progress: Extracting with granular status tracking
    await supabase
      .from('content')
      .update({
        processing_status: 'processing',
        transcript_status: 'processing',
        chapters_status: 'pending',
        last_transcript_attempt: new Date().toISOString(),
        transcript_error: null, // Clear previous error
        chapters_error: null,
        metadata: {
          currentStep: 'extracting',
          progress: 25
        }
      })
      .eq('id', contentId);
    
    const youtubeData = await getYouTubeData(videoId);
    
    // Update progress: Analyzing
    await supabase
      .from('content')
      .update({
        metadata: {
          currentStep: 'analyzing',
          progress: 60
        }
      })
      .eq('id', contentId);
    
    // Store YouTube URL in the youtube-content bucket
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('youtube-content')
      .upload(`${contentId}/metadata.json`, JSON.stringify({
        url,
        videoId,
        extractedAt: new Date().toISOString(),
        transcriptSource: youtubeData.metadata.transcriptSource,
        segmentCount: youtubeData.transcriptSegments.length
      }), {
        contentType: 'application/json',
        upsert: true
      });

    const storagePath = uploadData?.path || url;

    // Normalize transcript for cleaner AI processing
    const normalizedResult = normalizeTranscript(youtubeData.transcript);
    console.log(`YouTube transcript normalization: removed ${normalizedResult.fillerCount} fillers, fixed ${normalizedResult.repetitionCount} repetitions, ${normalizedResult.cleanupPercentage}% cleaned`);

    // Determine chapter status based on extraction results
    const chaptersStatus = youtubeData.chapters.length > 0 ? 'completed' : 'not_applicable';

    // Update content with extracted data and storage path
    const { error: contentError } = await supabase
      .from('content')
      .update({
        title: youtubeData.title,
        filename: youtubeData.title,
        storage_path: storagePath,
        text_content: normalizedResult.cleaned, // Use normalized for AI features
        chapters: youtubeData.chapters,
        processing_status: 'completed',
        transcript_status: youtubeData.metadata.hasRealTranscript ? 'completed' : 'failed',
        chapters_status: chaptersStatus,
        transcript_error: youtubeData.metadata.hasRealTranscript ? null : 'No transcript available, using description as fallback',
        last_chapters_attempt: youtubeData.chapters.length > 0 ? new Date().toISOString() : null,
        metadata: {
          ...youtubeData.metadata,
          chapters: youtubeData.chapters,
          extractedAt: new Date().toISOString(),
          hasTranscript: youtubeData.transcript.length > 0,
          hasChapters: youtubeData.chapters.length > 0,
          hasRealTranscript: youtubeData.metadata.hasRealTranscript,
          transcriptSource: youtubeData.metadata.transcriptSource,
          transcriptLanguage: youtubeData.metadata.transcriptLanguage,
          isAutoGenerated: youtubeData.metadata.isAutoGenerated,
          segmentCount: youtubeData.transcriptSegments.length,
          currentStep: 'completed',
          progress: 100,
          hasNormalizedTranscript: true,
          normalization: {
            fillerCount: normalizedResult.fillerCount,
            repetitionCount: normalizedResult.repetitionCount,
            cleanupPercentage: normalizedResult.cleanupPercentage,
            originalLength: normalizedResult.metadata.originalLength,
            cleanedLength: normalizedResult.metadata.cleanedLength
          }
        }
      })
      .eq('id', contentId);
    
    if (contentError) {
      console.error('Error updating content:', contentError);
      throw new Error('Failed to update content');
    }
    
    // Create or update recording entry with raw transcript and segments
    const { error: recordingError } = await supabase
      .from('recordings')
      .upsert({
        content_id: contentId,
        duration: youtubeData.duration,
        transcript: youtubeData.transcript, // Store raw for reference
        chapters: youtubeData.chapters,
        real_time_transcript: youtubeData.transcriptSegments, // Store timestamped segments
        processing_status: 'completed'
      });
    
    if (recordingError) {
      console.error('Error creating recording:', recordingError);
    }
    
    console.log(`YouTube extraction completed: ${youtubeData.title} (source: ${youtubeData.metadata.transcriptSource})`);
    
    return new Response(JSON.stringify({
      success: true,
      data: {
        ...youtubeData,
        // Don't include full segments in response to reduce payload
        transcriptSegments: undefined,
        segmentCount: youtubeData.transcriptSegments.length
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
    
  } catch (error) {
    console.error('YouTube extraction error:', error);
    
    // Update content with failed status and error details
    try {
      const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
      const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
      const supabase = createClient(supabaseUrl, supabaseServiceKey);
      const { contentId } = await req.clone().json().catch(() => ({}));
      
      if (contentId) {
        await supabase
          .from('content')
          .update({
            processing_status: 'failed',
            transcript_status: 'failed',
            transcript_error: error.message || 'Unknown extraction error'
          })
          .eq('id', contentId);
      }
    } catch (updateError) {
      console.error('Failed to update content status:', updateError);
    }
    
    return new Response(JSON.stringify({
      success: false,
      error: error.message
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
