// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbmkyiqhnjrfcooklnst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibWt5aXFobmpyZmNvb2tsbnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODg5MjIsImV4cCI6MjA2Mjg2NDkyMn0.SgJpDqWJTUvOR6hy0DCb0fAI8MwTwZTtA8o6KaaqGXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);